### PR TITLE
upload file_20201110

### LINKED ISSUE #3: Request 1 : Pull Request
무언가 새로운 것을 pull request 해주세요

### PR DESCRIPTION
**Pull request by milim203**
pull request test

### CODE REVIEW

**Comment by idjoopal** [comment]
무슨 내용을 request 하는 내용인가요?

**Comment by milim203** [comment]
I have added some on Plotly and github.

**Comment by milim203** [comment]
> 무슨 내용을 request 하는 내용인가요?

I have added some on Plotly and github.

**Comment by milim203** [comment]
> 무슨 내용을 request 하는 내용인가요?

I have added some on Plotly and github.

**Pull request merged**
